//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOMODO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona_Central
    {
        public int IdPersonaCentral { get; set; }
        public Nullable<int> IdPersona { get; set; }
        public Nullable<int> IdCentral { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Central Central { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
