//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOMODO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Peticion
    {
        public int IdPeticion { get; set; }
        public Nullable<int> IdSensor { get; set; }
        public string Estado { get; set; }
        public string Valor { get; set; }
        public string Accion { get; set; }
        public string NuevoVal { get; set; }
    
        public virtual Sensores Sensores { get; set; }
    }
}
