//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOMODO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int IdRegistro { get; set; }
        public Nullable<int> IdDispositivo { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> ValorAnalogicoActual { get; set; }
        public Nullable<bool> ValorDigitalActual { get; set; }
        public string Pin { get; set; }
        public Nullable<int> IdSensor { get; set; }
        public string TypoSensor { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
    }
}
