//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOMODO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sensores()
        {
            this.Peticion = new HashSet<Peticion>();
        }
    
        public int IdSensores { get; set; }
        public Nullable<int> IdDispositivo { get; set; }
        public string Nombre { get; set; }
        public string Pin { get; set; }
        public string TipoSensor { get; set; }
        public string Identificador { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual Dispositivo Dispositivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Peticion> Peticion { get; set; }
    }
}
